version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
matrix:
  include:
    - node_js: "0.6"
      env: TEST=true
  exclude:
    - node_js: "0.6"
      env: TEST=true ALLOW_FAILURE=true
